//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productdetail
    {
        public int Id { get; set; }
        public string product_name { get; set; }
        public string category_name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string short_des { get; set; }
        public string long_des { get; set; }
        public string small_img { get; set; }
        public string large_img { get; set; }
    }
}
